/*=============================================================================
  EV_Charging_System - FUNCTIONS
  =============================================================================*/

USE EV_Charging_System;
GO

-- ========================================
-- fn_CalculateChargingCost
-- Calculates total charging cost based on kWh, base price, and peak-hour multiplier.
-- ========================================
CREATE OR ALTER FUNCTION Operations.fn_CalculateChargingCost
(
    @Total_kWh          DECIMAL(13,4),
    @BasePrice_kWh      DECIMAL(19,4),
    @PeakHourMultiplier DECIMAL(3,2)
)
RETURNS MONEY
AS
BEGIN
    DECLARE @Cost MONEY;

    IF @Total_kWh IS NULL OR @Total_kWh <= 0
        RETURN 0;

    IF @BasePrice_kWh IS NULL OR @PeakHourMultiplier IS NULL
        RETURN 0;

    SET @Cost = CAST(@Total_kWh * @BasePrice_kWh * @PeakHourMultiplier AS MONEY);

    RETURN @Cost;
END;
GO

-- ========================================
-- fn_GetStationRevenue
-- Returns total revenue generated by a specific station within a date range.
-- ========================================
CREATE OR ALTER FUNCTION Reports.fn_GetStationRevenue
(
    @StationID INT,
    @FromDate  DATETIME2,
    @ToDate    DATETIME2
)
RETURNS MONEY
AS
BEGIN
    DECLARE @TotalRevenue MONEY;

    SELECT @TotalRevenue = SUM(s.CostTotal)
    FROM Operations.ChargingSession s
    JOIN Infrastructure.ChargingPoint p ON s.PointID = p.PointID
    WHERE p.StationID = @StationID
      AND s.Status = N'Đã sạc xong'
      AND s.StartTime >= @FromDate
      AND (s.EndTime IS NULL OR s.EndTime <= @ToDate);

    RETURN ISNULL(@TotalRevenue, 0);
END;
GO

PRINT N'Functions created successfully.';
GO
